# Criando um Classificador com TF-IDF

## Importando as bibliotecas necessárias

In [1]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import cross_val_score
import pandas as pd

## Aplicando o TF-IDF
- Existem duas classes no Scikit-Learn para aplicar o TF-IDF: TfidfTransformer e TfidfVectorizer
- TfidfTransformer: Transforma uma matriz de contagem de termos em uma matriz de valores TF-IDF
- TfidfVectorizer: Combina as funções de CountVectorizer e TfidfTransformer em uma única classe

In [2]:
documents = [
    "This is a simple example of Bag of Words.",
    "In natural language processing, Bag of Words is a basic technique.",
    "Bag of Words represents text data in the form of word occurrence counts.",
    "This is is a complex example of Bag of Words.",
]

In [3]:
bow = CountVectorizer()
vec_bow = bow.fit_transform(documents)
pd.DataFrame(vec_bow.toarray(), columns=bow.get_feature_names_out())

,bag,basic,complex,counts,data,example,form,in,is,language,...,of,processing,represents,simple,technique,text,the,this,word,words
0,1,0,0,0,0,1,0,0,1,0,...,2,0,0,1,0,0,0,1,0,1
1,1,1,0,0,0,0,0,1,1,1,...,1,1,0,0,1,0,0,0,0,1
2,1,0,0,1,1,0,1,1,0,0,...,2,0,1,0,0,1,1,0,1,1
3,1,0,1,0,0,1,0,0,2,0,...,2,0,0,0,0,0,0,1,0,1

In [4]:
tfidf = TfidfTransformer()
vec_tfidf = tfidf.fit_transform(vec_bow)
pd.DataFrame(vec_tfidf.toarray(), columns=bow.get_feature_names_out())

,bag,basic,complex,counts,data,example,form,in,is,language,...,of,processing,represents,simple,technique,text,the,this,word,words
0,0.252109,0.000000,0.00000,0.000000,0.000000,0.380893,0.000000,0.000000,0.308365,0.000000,...,0.504218,0.000000,0.000000,0.483114,0.000000,0.000000,0.000000,0.380893,0.000000,0.252109
1,0.199444,0.382193,0.00000,0.000000,0.000000,0.000000,0.000000,0.301325,0.243949,0.382193,...,0.199444,0.382193,0.000000,0.000000,0.382193,0.000000,0.000000,0.000000,0.000000,0.199444
2,0.162952,0.000000,0.00000,0.312264,0.312264,0.000000,0.312264,0.246192,0.000000,0.000000,...,0.325904,0.000000,0.312264,0.000000,0.000000,0.312264,0.312264,0.000000,0.312264,0.162952
3,0.222378,0.000000,0.42614,0.000000,0.000000,0.335974,0.000000,0.000000,0.544000,0.000000,...,0.444756,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.335974,0.000000,0.222378

In [5]:
tfidf_vec = TfidfVectorizer()
vec_tfidf_2 = tfidf_vec.fit_transform(documents)
pd.DataFrame(vec_tfidf_2.toarray(), columns=tfidf_vec.get_feature_names_out())

,bag,basic,complex,counts,data,example,form,in,is,language,...,of,processing,represents,simple,technique,text,the,this,word,words
0,0.252109,0.000000,0.00000,0.000000,0.000000,0.380893,0.000000,0.000000,0.308365,0.000000,...,0.504218,0.000000,0.000000,0.483114,0.000000,0.000000,0.000000,0.380893,0.000000,0.252109
1,0.199444,0.382193,0.00000,0.000000,0.000000,0.000000,0.000000,0.301325,0.243949,0.382193,...,0.199444,0.382193,0.000000,0.000000,0.382193,0.000000,0.000000,0.000000,0.000000,0.199444
2,0.162952,0.000000,0.00000,0.312264,0.312264,0.000000,0.312264,0.246192,0.000000,0.000000,...,0.325904,0.000000,0.312264,0.000000,0.000000,0.312264,0.312264,0.000000,0.312264,0.162952
3,0.222378,0.000000,0.42614,0.000000,0.000000,0.335974,0.000000,0.000000,0.544000,0.000000,...,0.444756,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.335974,0.000000,0.222378

## Carregando o dataset 20 News Groups

In [6]:
train_data = fetch_20newsgroups(subset='train',data_home='./data/train', remove=('headers', 'footers', 'quotes'))
test_data = fetch_20newsgroups(subset='test',data_home='./data/test', remove=('headers', 'footers', 'quotes'))

In [7]:
train_df = pd.DataFrame.from_dict({'text':train_data.data,'target':train_data.target})
test_df = pd.DataFrame.from_dict({'text':test_data.data,'target':test_data.target})

In [8]:
train_df

                                                    text  target
0      I was wondering if anyone out there could enli...       7
1      A fair number of brave souls who upgraded thei...       4
2      well folks, my mac plus finally gave up the gh...       4
3      \nDo you have Weitek's address/phone number?  ...       1
4      From article <C5owCB.n3p@world.std.com>, by to...      14
...                                                  ...     ...
11309  DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...      13
11310  I have a (very old) Mac 512k and a Mac Plus, b...       4
11311  I just installed a DX2-66 CPU in a clone mothe...       3
11312  \nWouldn't this require a hyper-sphere.  In 3-...       1
11313  Stolen from Pasadena between 4:30 and 6:30 pm ...       8

[11314 rows x 2 columns]

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11314 entries, 0 to 11313
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    11314 non-null  object
 1   target  11314 non-null  int64
dtypes: int64(1), object(1)
memory usage: 176.9+ KB

In [10]:
train_df['target'].value_counts()

10    600
15    599
8     598
9     597
11    595
7     594
13    594
5     593
14    593
2     591
12    591
3     590
6     585
1     584
4     578
17    564
16    546
0     480
18    465
19    377
Name: target, dtype: int64

## Aplicando Pré-processamento nos dados

In [11]:
import re
import string
re_url = re.compile(r'https?://\S+')
re_email = re.compile(r'\S+@\S+\.\S+')

def clean_text(text):
    text = text.lower().strip()
    text = re.sub(re_url, 'URL', text)
    text = re.sub(re_email, 'EMAIL', text)
    text = re.sub(f'[{re.escape(string.punctuation)}]', '', text)
    # text = re.sub(r'\d+', ' ', text)
    # text = re.sub(r'\s+', ' ', text)
    return text

In [12]:
train_df.head()

                                                text  target
0  I was wondering if anyone out there could enli...       7
1  A fair number of brave souls who upgraded thei...       4
2  well folks, my mac plus finally gave up the gh...       4
3  \nDo you have Weitek's address/phone number?  ...       1
4  From article <C5owCB.n3p@world.std.com>, by to...      14

In [13]:
train_df['text'] = train_df['text'].apply(clean_text)
test_df['text'] = test_df['text'].apply(clean_text)

In [14]:
train_df.head()

                                                text  target
0  i was wondering if anyone out there could enli...       7
1  a fair number of brave souls who upgraded thei...       4
2  well folks my mac plus finally gave up the gho...       4
3  do you have weiteks addressphone number  id li...       1
4  from article EMAIL by EMAIL tom a baker\n\n\nm...      14

## Aplicando o CountVectorizer

In [15]:
cv = CountVectorizer()

X_train = cv.fit_transform(train_df['text'])

X_train

<11314x101577 sparse matrix of type '<class 'numpy.int64'>'
	with 1064531 stored elements in Compressed Sparse Row format>

In [16]:
print(cv.get_feature_names_out())

['00' '000' '0000' ... 'zzzzzzt' '³ation' 'úz']

In [17]:
cv = CountVectorizer(min_df=0.001, lowercase=True, stop_words='english')

X_train = cv.fit_transform(train_df['text'])

X_train

<11314x8446 sparse matrix of type '<class 'numpy.int64'>'
	with 546173 stored elements in Compressed Sparse Row format>

## Construindo o pipeline

In [18]:
bow = CountVectorizer(min_df=0.001, lowercase=True, stop_words='english')
tfidf = TfidfTransformer()
model = LogisticRegression()

bow_pipe = Pipeline([('bow', bow),('model', model)])

tfidf_pipe = Pipeline([('bow', bow), ('tfidf', tfidf),('model', model)])

## Treinando modelo com o pipeline

In [19]:
resultados_bow = cross_val_score(bow_pipe, train_df['text'], train_df['target'], cv=5, n_jobs=-1, scoring='accuracy')
print(resultados_bow.mean())

0.6521132445096667

In [20]:
resultados_tfidf = cross_val_score(tfidf_pipe, train_df['text'], train_df['target'], cv=5, n_jobs=-1, scoring='accuracy')
print(resultados_tfidf.mean())

0.7074422933337708